settings:
  auto-pickup-perm: 'auto.pickup'
  auto-block-perm: 'auto.block'
  auto-mob-perm: 'auto.mob'
  auto-mine-perm: 'auto.mine'

  mode:
    active: '&aActive'
    passive: '&cPassive'

  auto-block-items:
    'DIAMOND':
      amount: 9
      type: 'DIAMOND_BLOCK'
    'EMERALD':
      amount: 9
      type: 'EMERALD_BLOCK'

gui-main:
  title: 'Pickup Menu'
  size: 3
  items:
    block-drops:
      type: 'EMERALD_BLOCK'
      name: '&2Block drops'
      glow: false
      amount: 1
      datavalue: 0
      lore:
        - ''
        - '&aClick to enable/disable'
        - '&aauto block drops.'
        - ''
        - '&fMode: %mode%'
      nbt: '{}'
      slot: 10
    mob-drops:
      type: 'DIAMOND_SWORD'
      name: '&2Mob drops'
      glow: false
      amount: 1
      datavalue: 0
      lore:
        - ''
        - '&aClick to enable/disable'
        - '&aauto mob drops.'
        - ''
        - '&fMode: %mode%'
      nbt: '{}'
      slot: 12
    block-translator:
      type: 'QUARTZ_BLOCK'
      name: '&2Block translator'
      glow: false
      amount: 1
      datavalue: 0
      lore:
        - ''
        - '&aClick to enable/disable'
        - '&aauto block drops.'
        - ''
        - '&fMode: %mode%'
      nbt: '{}'
      slot: 14
    mine-smelt:
      type: 'IRON_INGOT'
      name: '&2Mine Smelter'
      glow: false
      amount: 1
      datavalue: 0
      lore:
        - ''
        - '&aClick to enable/disable'
        - '&amine smelter.'
        - ''
        - '&fMode: %mode%'
      nbt: '{}'
      slot: 16